### ISSUE TITLE
Error setting activity: No valid cover URL found

### ISSUE THREAD

**Issue by NovumGain** [0xGingi/audiobookshelf-discord-rpc#1]
First of all, when I tried to get it working, I had to rename all the variables in the config to different things, which was odd ,but meh -- I did so, everything started working, except 1. the status didn't show up, and 2. there's an error. The title of this; But that said, it's a japanese audiobook.. but even so -- it's found on Audible.co.jp; any ideas?

**Comment by NovumGain** [comment]
While looking inside your code, I couldn't figure out why it wasn't found -- AudioBookShelf is the one who found the cover url for the actual in-web pictures.

**Comment by NovumGain** [comment]
After looking into it further, for some reason, my 10.147.20.1:1337/api/search/covers is returning "bad request", whereas anything else was another error (something akin to not being found).

**Comment by 0xGingi** [comment]
Provider defaults to US Audible, it's on line 196, I'll add it as a config option when I have time

**Comment by 0xGingi** [comment]
https://github.com/0xGingi/audiobookshelf-discord-rpc/releases/tag/v1.4.2

Please try the new release, if no match is found, it'll try another provider, and if no cover art is found at all, it should still work

**Comment by 0xGingi** [comment]
I've also updated the installer to provide the newer config names, thanks for submitting these bugs

**Comment by NovumGain** [comment]
Apologies in the delay in my reply; it's functioning beautifully now. Thank you :)

Have a good one!
